version: "3.9"

services:

  mariadb:
    image: mariadb:10
    restart: always
    container_name: mariadb
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d

  nginx_proxy:
    image: nginx:1.20-alpine
    container_name: nginx_proxy
    restart: on-failure
    ports:
      - ${NGINX_PROXY_PORT}:${NGINX_PROXY_PORT}
      # - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # certbot:
  #   depends_on:
  #     - nginx_proxy
  #   image: certbot/certbot
  #   container_name: certbot
    # volumes:
    #   - ./certbot-etc:/etc/letsencrypt
    # command: certonly --dry-run --webroot --webroot-path=/usr/share/nginx/html --email test@test.com --agree-tos --no-eff-email --keep-until-expiring -d mingwanseo.com -d www.mingwanseo.com

  frontend:
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./packages/frontend/src:/usr/src/app/src
    command: "npm start"

  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    volumes:
      - ./packages/backend:/svr/app
      - ./scripts/wait.sh:/wait.sh
      - /svr/app/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mariadb
    links:
      - mariadb


